name: Update staging
on:
  push:
    branches:
      - main
jobs:
  push-to-staging-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        name: Push changes to staging branch
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          repoWithToken="https://"$PAT"git@github.com:qburst-arundev/test.git"
          git init
          git remote set-url origin $repoWithToken
          git branch -M staging
          git add --all
          git push --force -u origin staging
