name: dev-environ-workflow
on:
  push:
    branches:
      - main
jobs:
  push-to-test-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
       
      - shell: bash
        name: Push changes to test branch
        run: git push -f origin HEAD:staging
